---
title: "幽门螺杆菌(H. polyri)感染和血糖水平有关系吗？"
subtitle: "数据分析从线索到数据证据"
author: 陈琼
date: 2023-10-06
categories:
  - 数据处理
  - 论文写作
bibliography: HP.bib
draft: true
---

最近拿到了某个医院的常规体检数据，变量有年龄、性别、BMI、血压、空腹血糖、糖化血红蛋白、C13和C14等，我们想通过数据做一些探索性的分析，看看幽门螺杆菌感染(H. pylori)是否与血糖水平相关？

## 文献回顾
幽门螺杆菌(H. Polyri, HP)感染和糖尿病是两个相对独立的常见疾病。研究发现HP感染与胰岛素抵抗 [@dogan2015]、代谢综合征、炎性反应等相关[@SongShuRan2016; @kayar2015]，糖尿病患者中HP感染率较高，而HP根除率较正常人低[@c2014]，且清除之后的再感染率更高 [@m2012]。

一些样本量较大的人群研究也发现HP感染和糖尿病相关的症状、体征或并发症相关。
同济东风队列的一项横断面研究，纳入了30810研究对象，结果发现H. polyri感染与二型糖尿病发病风险相关 [@han2016]。另外一项纳入了73824例体检人群的回顾性研究发现，H. polyri感染与糖尿病视网膜病变发病风险相关[@liu2023]。

**与HP感染相关的糖尿病相关症状体征：**

- 胰岛素抵抗
- 代谢综合征
- 炎性反应
- 二型糖尿病
- 糖尿病视网膜病变

**HP感染与糖尿病机制研究**

目前HP感染对糖尿病发生发展的影响机制不明确，而糖尿病患者HP感染率高的原因可能如下：

- 糖尿病患者免疫功能紊乱
- 胃肠功能紊乱
- **胃粘膜非酶糖基化**

导致HP更容易植入胃粘膜，从而增加HP感染概率。

糖尿病患者HP感染根除率低可能的原因如下：

- 抗生素耐药性增加
- 抗生素生物利用度下降

HP感染可能导致系统性炎症和血管内皮损伤，HP感染也可能通过影响瘦素和胃饥饿素的水平，从而影响脂质代谢和胰岛素敏感性。

**相关知识点：**

- HP感染率在40%只70%之间波动。
- HP感染通过升高C反应蛋白和IL-6等炎性因子水平从而心脑血管疾病和代谢综合征，而这些因子与糖尿病致病机制相关。
- 既往研究中*HP感染与糖尿病风险之间的关系*结果不一致。
 