---
title: "英语学习词汇本"
author: "陈琼"
date: 2023-10-27
categories: ["英语学习"]
tags: ["生词本"]
---

这篇博文用来记录我在英语学习过程中遇到的一些比较陌生的词汇，以便随后翻看学习。

## [The daily grind / daily routine](https://youtu.be/OIyg0sfACj0)

::: {.li-cards}

- daily grind / daily routine
- when a rooster crow
- my alarm goes off at 7 am
- make the bed
  - that's where you put the blankets and the pillows back in a nice tidy order
- use the bathroom/ go to the bathroom
- put on something
  - put on make up, put on lipstick, put on mascara, and put on eye shadow
- clean shaven
- grab your things

:::


## [using things](https://youtu.be/F03udaSuULg)

::: {.li-cards}
- extend
- retract
- stack
- insert
  - insert the pen to the cap
- crumple
  - crumple the paper
- eject
  - eject button, press the eject button to eject the DVD
- rearrange
  - rearrange something
- clamp
  - I need a light that could clamp to my desk
- fold up
  - fold up the table
- put up
  - attach something up to something
- wind up
- crank
  - crank the wheel
- slide 
  - you can slide a door open
- zip/unzip
  - zip up the 
- spin
  - spin the tire, if you spin somethins, something can turn
- box up / unbox
  - put something in box, box up all these stuff
- tighten / loosen
- wrap
  - wrap something, put something around it
- plunge
  - if your toilet doesn't flush 
:::

## Tree related words

::: {.li-cards}
- trunk
  - 树干
- branch
  - 树枝
- twig
  - 小树枝
- leaf
  - 树叶
- tree scar
  - 树疤
- tree knot
  - 树结
- blossom
  - 树开花
- bark
  - 树皮
:::