---
title: "英语学习计划"
author: "陈琼"
date: 2020-20-26
categories: ["英语学习"]
---

我在油管频道上看到一位外教老师帮助非英语母语者制定的英语学习计划，我觉得很好。我也一直想把我的英语口语进行一个提升，特别是小果仁开始学习英语之后，我也想给她做一个榜样，希望通过我的坚持学习能够让她在学习语言的道路上能够坚持下去。我根据自己的实际情况对这个计划进行了调整，希望自己能坚持学习下去。

你也可以点击这里查看[原始清单](https://youtu.be/5-T6Xqlh6BU),下面的清单是我根据自己的实际情况进行调整和设定的详细执行计划。

## 准备清单

- 1 hour per day (30 minutes will work as well).
  - 周一: 17:30 -- 19:30 (果仁语言课的等待时间)
  - 周二: 17:30 -- 18:30（工作后时间）
  - 周三: 19:00 -- 20:30 (果仁英语课的等待时间)
  - 周四: 17:30 -- 19:30 (果仁舞蹈课的等待时间)
  - 周五: 适宜时间选择下周学习材料
  - 周六: 10:40 -- 12:00 (果仁英语课的等待时间)
  - 周日：适宜时间选择下周学习材料
- a notebook and a pen to write down new vocabulary each day.
  - 计划记录到learning-notes网页中，所以准备一台笔记本电脑就好
- an English song.
- an English a book.
- an English TV show.

## 周一

(Spend 30-40 minutes Reading)

- Read your book.
- Read the news.
- Read an article on http://simple.wikipedia.com
- Write down some new words in your notebook with their definition.
- Spend the rest of your hour:
  - Reading out loud from your book
  - Writing out some passages from your book.
  - Listening to the audiobook of your book.
  - Using Duolingo or other learning apps.

## 周二

(Spend 30-40 minutes Writing)

- Write what you did yesterday, today, and tomorrow in your notebook.
- Write a few comments on Youtube videos.
- Write some sentences about what you like and dislike about your song, your book, and your TV show.
- Write a summary of what you have read in your book the day before.
- Put some new words in your dictionary.
- Spend the rest of your hour:
 - Reading what you have written.
 - Listening to what you have written by pasting your writing into Google translate and have it read it to you.
 - Reading what you have written out loud.
 - Using Duolingo or other learning apps.

## 周三

(Spend 30-40 minutes Listening)

- Watch your TV show.
- Listen to your song.
- Listen to the Audiobook of your book if you have it.
- Watch a few Youtube videos.
- Put new words in your dictionary.
- Spend the rest of your hour:
 - Read about your TV show.
 - Write about how your song makes you feel.
 - Mimic or shadow people from your TV show.
 - Sing along to your song.

## 周四

(Spend 30-40 minutes Speaking)

- Hire a tutor on:
  - Preply: http://tracking.preply.com/SH2X
  - Cambly: http://cambly.com
  - iTalki: http://italki.com
- Talk out loud.
  - Narrate your life.
  - Record yourself and play it back.
  - Put words in your dictionary.
  - Spend the rest of your hour:
  - Reading out loud.
  - Singing out loud.
  - Shadowing or mimicking actors from your TV show.

## 周五

(Spend the Entire hour on Vocabulary)

- Review all the words in your dictionary.
- Write them out.
- Say them out loud.
- Use them in a sentence.
- Make a http://quizlet.com set.
- Make flashcards.
- Work until you have them all memorized.

## 周末

- Find a new song.
- Find a new book.
- Find a new TV show.
- Take a break.