---
title: "quarto文档中使用mermaid实现思维导图"
author: "陈琼"
date: 2023-10-23
categories: ["quarto"]
tags: ["mermaid"]
execute: 
  echo: fenced
---

> 思维导图是我们组织想法的常用工具,能够实现这种功能的工具有很多,比如说XMind、Gitmind、MindMaster、MindNote等。而在Quarto里，我们可以使用Mermaid工具实现思维导图，从而输出到网页、word、PDF等。

今天我把学习在Quarto中使用Meimaid绘制思维导图的过程记录如下。如果在此之前你还没有了解过Quarto的话，请查看这篇文章，[论文写作效率神器:Quarto出版系统](http://chenq.site/qsight/2023-3-25-quarto-writing/)，先了解一下Quarto。

首先，浏览一下Mermaid的[官方网站](https://mermaid.js.org/intro/)，mermaid除了可以绘制思维导图之外还可以绘制流程图、饼图、关系图等，是一个很方便的工具。

之后，在quarto文档中插入mermaid的代码块，即可开始思维导图的绘制。


## 基本语法

在mermaid中，思维导图以mindmap关键字开头，然后另起一行缩进空格写思维导图的根节点，然后另起一行，在根节点的基础上再缩进空格写第二级节点，相同级别的节点需要缩进相同的空格数。再往下添加节点的话，依据同样的准则即可。

具体写法和实现效果可以参考下面的代码。

```{mermaid}
mindmap
  质量控制
    可比性
      发病时间定义
      疾病编码
    完整性
      M:I
      发病率
      死亡率
      年龄别率
    有效性
      MV\%
    时效性
```

## 控制节点图形

mermaid目前的语法可以让我们通过不同的***括号语句***控制节点的图形，比如通过方括号对\[长方形\]显示长方形,通过\(圆角长方形\)显示圆角长方形，具体可参考下面的代码。

```{mermaid}
mindmap
  形状
    默认形状
    [长方形]
    (圆角长方形)
    ((圆形))
    ))爆炸形状((
    )云朵形状(
    {{六角形}}
```

## 添加图标

```{mermaid}
mindmap
  讲话
  ::icon(fa fa-microphone)
      笔记本
      ::icon(fa fa-book)
```


## CSS类调整格式

Mermaid在绘制思维导图的时候，可以通过三个冒号 \:\:\: 后面跟着以空格分割的多个CSS类名称。

比如,我们在CSS文件里定义了一个CSS类

```css
.important{
  font-size: 3em;
  font-weight: bold;
}

. red{
  text-color: darkred;
}
```

我们在上面的CSS文件里定义了两个CSS类,名称分别为 important 和 red , 那么我们就可以在下面的mermaid语句引用该类来自定义节点的显示效果。

使用方法是：在适用的节点下面一行，与该节点缩进相同的单位，然后使用三个冒号跟着以空格分隔的CSS类名即可。

```{mermaid}
mindmap
    Root
        A[自定义显示效果]
        :::important red
        B(B)
        C
```



## 在线练习

[mermaid提供了在线的渲染工具](https://mermaid.live/edit#pako:eNpVjk2Lg0AMhv9KyGkL9Q94WGh1t5fCFurN6SFo7AztfDBGpKj_fcd62c0pvM_zhkzY-JYxx-7px0ZTFKhK5SDNoS50NL1Y6m-QZZ_ziQWsd_ya4fhx8tBrH4Jx993mH1cJium8agyijXssGyre_R_HM5T1mYL4cPtLqtHP8FWbi07n_xMdObW-647yjrKGIhQU3wru0XK0ZNr0_rQmCkWzZYV5WlvuaHiKQuWWpNIg_vpyDeYSB97jEFoSLg3dI9ktXH4B_cJWqw), 我们可以直接在这里输入相应的语句, 然后网站会自动渲染出结果。



